name: GitHub Actions Demo
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Use Docker
        uses: 'docker'
      - name: Build
        run: docker build -t dockerdemo .
      - name: Tag
        run: docker tag dockerdemo docker.pkg.github.com/tourcoder/dockerdemo/dockerdemo:latest
      - name: Deploy
        run: docker push docker.pkg.github.com/tourcoder/dockerdemo/dockerdemo:latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}



